#!/usr/bin/env python3
"""Emit a CORRECTION migration for worked_solution content already live on
the site, plus the removal of question_assets rows that are no longer
referenced (a figure that turned out to be typed text instead, per the
Equation.DSMT4 rule -- see extract_acjc_p1_answers.py's module docstring
for the ACJC 2024 H2 P1 case this was first built for).

Unlike gen_answers_migration.py (which SETS worked_solution for the first
time and additively INSERTs assets, guarded by a "must currently be
NULL/absent" preflight), this migration OVERWRITES rows that already carry
a value -- the paper has already been published and the fix is correcting
what's live, not laying it down fresh. Both the UPDATE and the DELETE are
naturally idempotent (setting a column to a fixed value, or deleting a row
that may already be gone, are each safe to repeat), so there is no
NULL-guard here; the preflight only confirms the expected ROW SET exists
(right paper, right type, right question numbers) before touching anything.

Usage:
  python3 -m ingest.gen_answers_fix_migration <worked_solutions_fix.json> \\
      <dest.sql> [--school ACJC] [--year 2024] [--paper 1] [--level H2] \\
      [--type mcq] [--drop-assets '[[1,"ans"],[12,"ans"],[14,"ans"]]']

`worked_solutions_fix.json`: {"1": "<div class=\\"worked-solution\\">...</div>", ...}
  -- ONLY the questions whose worked_solution is changing.

`--drop-assets`: a JSON list of [question_number, slot] pairs to DELETE
  from question_assets -- for a figure that turned out not to need an
  asset row at all (typed as text instead). Optional; omit for a fix that
  only touches worked_solution text.
"""
from __future__ import annotations
import argparse
import json
from pathlib import Path

TAG = "$qp$"


def _lit(s: str) -> str:
    if TAG in s:
        raise SystemExit("dollar-quote tag %s occurs inside a value" % TAG)
    return TAG + s + TAG


def main(ws_json: str, dest: str, *, school: str = "ACJC", year: int = 2024,
        paper: int = 1, level: str = "H2", qtype: str = "mcq",
        drop_assets_json: str | None = None):
    worked = json.loads(Path(ws_json).read_text(encoding="utf-8"))
    QNUMS = sorted(int(q) for q in worked.keys())

    DROP = []
    if drop_assets_json:
        DROP = [(int(q), slot) for q, slot in json.loads(drop_assets_json)]

    WHERE = ("p.school = '%s' AND p.year = %d AND p.paper_number = %d "
             "AND p.level = '%s'" % (school, year, paper, level))

    L: list = []
    add = L.append

    add("-- %s %d %s P%d -- worked_solution CORRECTION (%d question(s)%s)"
        % (school, year, level, paper, len(QNUMS),
           ", %d orphaned asset row(s) dropped" % len(DROP) if DROP else ""))
    add("-- Generated by gen_answers_fix_migration.py. DRY RUN: ends in ROLLBACK.")
    add("-- This CORRECTS rows the paper's first answers-stage migration already")
    add("-- set -- both the UPDATE and the DELETE below are idempotent (safe to")
    add("-- run more than once), so there is no NULL/absence guard, only a check")
    add("-- that the expected question rows exist.")
    add("")
    add("BEGIN;")
    add("")
    add("DO $preflight$")
    add("DECLARE n int;")
    add("BEGIN")
    add("  SELECT count(*) INTO n FROM questions q JOIN papers p ON p.id = q.paper_id")
    add("   WHERE %s AND q.type = '%s'" % (WHERE, qtype))
    add("     AND q.question_number IN (%s);" % ", ".join(str(q) for q in QNUMS))
    add("  IF n <> %d THEN" % len(QNUMS))
    add("    RAISE EXCEPTION 'expected %d question(s), matched %%', n;" % len(QNUMS))
    add("  END IF;")
    add("END")
    add("$preflight$;")
    add("")

    for q in QNUMS:
        html = worked[str(q)]
        add("UPDATE questions q SET worked_solution = %s" % _lit(html))
        add("  FROM papers p")
        add(" WHERE p.id = q.paper_id AND %s" % WHERE)
        add("   AND q.type = '%s' AND q.question_number = %d" % (qtype, q))
        add(" RETURNING q.question_number, length(q.worked_solution) AS html_chars;")
        add("")

    if DROP:
        add("-- Orphaned asset rows: the figure these referenced is now typed")
        add("-- text (span.frac) instead, so no question_assets row should")
        add("-- remain for it. DELETE...USING, idempotent if already gone.")
        add("DELETE FROM question_assets a")
        add(" USING questions q, papers p")
        add(" WHERE a.question_id = q.id AND q.paper_id = p.id AND %s" % WHERE)
        add("   AND q.type = '%s'" % qtype)
        add("   AND (q.question_number, a.slot) IN (%s)"
            % ", ".join("(%d, %s)" % (qn, _lit(slot)) for qn, slot in DROP))
        add("RETURNING a.question_id, a.slot, a.storage_path;")
        add("-- Expect %d row(s) deleted (0 if this migration already ran)." % len(DROP))
        add("")

    add("-- Flip to COMMIT when the above looks right.")
    add("ROLLBACK;")
    add("")
    add("-- VERIFICATION -- run SEPARATELY, after COMMIT:")
    add("-- select q.question_number, length(q.worked_solution) as ws_chars,")
    add("--        string_agg(a.slot, ',' order by a.ordinal)")
    add("--          filter (where a.slot like 'ans-%' or a.slot = 'ans') as ans_slots")
    add("--   from questions q join papers p on p.id = q.paper_id")
    add("--   left join question_assets a on a.question_id = q.id")
    add("--  where %s and q.question_number in (%s)"
        % (WHERE, ", ".join(str(q) for q in QNUMS)))
    add("--  group by q.question_number, q.worked_solution")
    add("--  order by q.question_number;")

    bad = [l for l in L if "%%" in l]
    bad = [l for l in bad if "RAISE EXCEPTION" not in l]
    if bad:
        raise SystemExit("emitted SQL contains an unexpected literal %%%%:\n  "
                         + "\n  ".join(bad))

    Path(dest).write_text("\n".join(L) + "\n", encoding="utf-8")
    print("wrote", dest)
    print("  %d question(s) corrected, %d asset row(s) to drop"
          % (len(QNUMS), len(DROP)))


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("ws_json", help="{qnum: html} -- only the changed questions")
    ap.add_argument("dest")
    ap.add_argument("--school", default="ACJC")
    ap.add_argument("--year", type=int, default=2024)
    ap.add_argument("--paper", type=int, default=1)
    ap.add_argument("--level", default="H2")
    ap.add_argument("--type", dest="qtype", default="mcq")
    ap.add_argument("--drop-assets", dest="drop_assets_json", default=None,
                    help='JSON list of [question_number, slot] pairs to delete')
    a = ap.parse_args()
    main(a.ws_json, a.dest, school=a.school, year=a.year, paper=a.paper,
        level=a.level, qtype=a.qtype, drop_assets_json=a.drop_assets_json)
