#!/usr/bin/env python3
"""Emit the paper + questions + assets migration for a STRUCTURED (P2/P3)
question paper.

The structured-paper sibling of `gen_question_migration.py` (MCQ): same
one-statement-CTE shape, same pre-flight guards, same dry-run-ends-in-ROLLBACK
contract (handoff SS8/SS9/SS11) -- kept as a SEPARATE file because the two
question shapes differ in exactly the columns that matter for safety:

* No `options` / `answer_key` -- a structured question has neither; both are
  left NULL rather than emitting an MCQ-shaped value that means nothing here.
* `type = 'structured'`, not `'mcq'`.
* `marks` is the QUESTION's own printed total (`questions.json`'s "marks",
  itself already cross-checked against "parts sum to N" during extraction),
  not a constant 1 -- an MCQ's marks column is always 1 as of this writing,
  a structured question's is not.
* No answer-key file to read or cross-check against (there's no `answer_key`
  column to fill), so this script takes one fewer argument than the MCQ one.

Usage:
  python3 -m ingest.gen_parts_migration <outdir> <dest.sql> \\
      [--school RI --year 2024 --paper 2 --level H2 --assessment prelim]

The `question_assets` INSERT is omitted whenever `asset_plan.json` has no
rows (an empty VALUES list is not valid SQL) -- but for a paper whose figures
are being HAND-cropped (`extract_parts.py --manual-assets`), the plan can
easily be non-empty (it names the files the user needs to crop TO) well
before those files exist anywhere, unlike the auto-crop flow, where planning
and cropping happen together and a non-empty plan always means the images
already exist. `--skip-assets` (default: on) makes that gap explicit rather
than relying on plan emptiness to mean "not ready": this script always emits
the paper + questions, and only also emits `question_assets` when told
`--skip-assets=false`, i.e. once the images are actually uploaded to the
`question-assets` storage bucket.

IMPORTANT -- `--skip-assets=false` is for a paper that is NOT loaded yet
(paper + questions + assets, all in the one insert, still-fresh outdir).
It is NOT the way to attach assets to a paper that was ALREADY loaded in an
earlier, separate run of this same script: re-running THIS script against
an already-live paper still re-emits the paper + questions INSERT, and the
pre-flight guard correctly refuses ("already loaded") -- refusing safely,
but also refusing to attach anything. For that case (the normal
diagrams-uploaded-after-the-fact flow) use
`gen_parts_assets_migration.py` instead: it only touches `question_assets`,
resolving question ids via a paper-identity JOIN rather than re-inserting
rows that already exist.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

TAG = "$qh$"


def _lit(s: str) -> str:
    """Dollar-quote a value, having checked the delimiter is not inside it.

    Handoff SS11: test for the ACTUAL tag, not a substring of it.
    """
    if TAG in s:
        raise SystemExit("dollar-quote tag %s occurs inside a value" % TAG)
    return TAG + s + TAG


def main(outdir: str, dest: str, *,
        school: str = "RI", year: int = 2024, paper: int = 2, level: str = "H2",
        assessment: str = "prelim", skip_assets: bool = True):
    SCHOOL, YEAR, PAPER, LEVEL, ASSESSMENT = school, year, paper, level, assessment
    out = Path(outdir)
    rows = json.loads((out / "questions.json").read_text(encoding="utf-8"))
    plan = json.loads((out / "asset_plan.json").read_text(encoding="utf-8"))
    if skip_assets:
        plan = []

    missing_marks = [r["question_number"] for r in rows if r["marks"] is None]
    if missing_marks:
        raise SystemExit("no marks total for question(s) %s -- the paper's "
                         "own '[Total: N]' line was not found or not parsed"
                         % missing_marks)

    L: list = []
    add = L.append
    add("-- %s %d %s Paper %d -- paper + %d structured questions + %d assets"
        % (SCHOOL, YEAR, LEVEL, PAPER, len(rows), len(plan)))
    add("-- Generated by gen_parts_migration.py. DRY RUN: ends in ROLLBACK.")
    add("-- Flip ROLLBACK to COMMIT once the output looks right, then confirm")
    add("-- with the SEPARATE verification SELECT at the bottom (SS9: a dry run")
    add("-- and a real commit print identical output).")
    add("")
    add("BEGIN;")
    add("")
    add("-- ---------------------------------------------------------------")
    add("-- PRE-FLIGHT. No unique constraint exists on papers or questions,")
    add("-- so a second run would duplicate the entire paper in silence.")
    add("-- ---------------------------------------------------------------")
    add("DO $preflight$")
    add("DECLARE n int;")
    add("BEGIN")
    add("  -- this exact paper must not already be loaded. LEVEL is part of")
    add("  -- the key: a school's H1 paper of the same number can otherwise")
    add("  -- share school, year and paper_number with this one.")
    add("  SELECT count(*) INTO n FROM papers")
    add("   WHERE school = %s AND year = %d AND paper_number = %d"
        % (_lit(SCHOOL), YEAR, PAPER))
    add("     AND level = '%s';" % LEVEL)
    add("  IF n <> 0 THEN")
    add("    RAISE EXCEPTION '%s %d %s P%d is already loaded (%% paper row(s)) "
        "-- re-running would duplicate it', n;" % (SCHOOL, YEAR, LEVEL, PAPER))
    add("  END IF;")
    add("END")
    add("$preflight$;")
    add("")
    add("-- ---------------------------------------------------------------")
    add("-- One statement: paper, questions and assets, or none of them.")
    add("-- status is set EXPLICITLY on both paper and questions -- the column")
    add("-- defaults to 'pending', which inserts fine and is then invisible to")
    add("-- every non-reviewer. type = 'structured': no options, no answer_key")
    add("-- -- a structured question has neither, so both are left NULL rather")
    add("-- than an MCQ-shaped value that would mean nothing here.")
    add("-- ---------------------------------------------------------------")
    add("WITH p AS (")
    add("  INSERT INTO papers (school, year, paper_number, level, paper_name,")
    add("                      is_prelim, assessment_type, status, source_type)")
    add("  VALUES (%s, %d, %d, '%s', NULL, true, '%s', 'approved', 'docx')"
        % (_lit(SCHOOL), YEAR, PAPER, LEVEL, ASSESSMENT))
    add("  RETURNING id")
    add(")")
    if plan:
        add(", q AS (")
    add("  INSERT INTO questions (paper_id, type, question_number, section_label,")
    add("                         content_html, content_text, marks, status)")
    add("  SELECT p.id, 'structured', v.qn, v.sec, v.html, v.txt, v.marks, 'approved'")
    add("    FROM p, (VALUES")
    vals = []
    for r in sorted(rows, key=lambda r: r["question_number"]):
        qn = r["question_number"]
        sec = _lit(r["section"]) if r.get("section") else "NULL"
        vals.append("      (%d, %s, %s, %s, %d)"
                    % (qn, sec, _lit(r["content_html"]), _lit(r["content_text"]),
                       r["marks"]))
    add(",\n".join(vals))
    add("    ) AS v(qn, sec, html, txt, marks)")
    if plan:
        add("  RETURNING id, question_number")
        add(")")
        add("INSERT INTO question_assets (question_id, slot, storage_path, ordinal)")
        add("SELECT q.id, a.slot, a.path, a.ord")
        add("  FROM q JOIN (VALUES")
        arows = []
        for a in sorted(plan, key=lambda a: (a["question"], a["ordinal"])):
            arows.append("    (%d, %s, %s, %d)"
                         % (a["question"], _lit(a["slot"]),
                            _lit(a["storage_path"]), a["ordinal"]))
        add(",\n".join(arows))
        add("  ) AS a(qn, slot, path, ord) ON a.qn = q.question_number")
        add("RETURNING question_id, slot, storage_path, ordinal;")
    else:
        add("  RETURNING id, question_number;")
    add("")
    if plan:
        add("-- Expect %d asset rows returned." % len(plan))
    elif skip_assets:
        add("-- No question_assets inserted (--skip-assets, the default): "
            "diagrams are hand-cropped, and the images are not yet uploaded "
            "to the question-assets bucket. Re-run with --skip-assets=false "
            "once they are, to attach them in a follow-up migration.")
    else:
        add("-- No question_assets inserted -- asset_plan.json has no rows "
            "(no figures in this paper, or none planned yet).")
    add("")
    add("-- Flip to COMMIT when the above looks right.")
    add("ROLLBACK;")
    add("")
    add("-- ---------------------------------------------------------------")
    add("-- VERIFICATION -- run SEPARATELY, after COMMIT.")
    add("-- ---------------------------------------------------------------")
    add("-- select q.question_number, q.marks,")
    add("--        length(q.content_html)              as html_chars,")
    add("--        length(q.content_text)              as text_chars,")
    add("--        q.content_search is not null        as searchable,")
    add("--        count(a.id)                         as assets,")
    add("--        string_agg(a.slot, ',' order by a.ordinal) as slots")
    add("--   from questions q")
    add("--   left join question_assets a on a.question_id = q.id")
    add("--   join papers p on p.id = q.paper_id")
    add("--  where p.school = '%s' and p.year = %d" % (SCHOOL, YEAR))
    add("--    and p.paper_number = %d and p.level = '%s'" % (PAPER, LEVEL))
    add("--  group by q.question_number, q.marks,")
    add("--           q.content_html, q.content_text, q.content_search")
    add("--  order by q.question_number;")
    add("-- Expect %d rows, every searchable = true, %d assets in total."
        % (len(rows), len(plan)))

    bad = [l for l in L if "%%" in l]
    if bad:
        raise SystemExit("emitted SQL contains a literal %%%% -- see "
                         "gen_tag_migration.py:\n  " + "\n  ".join(bad))
    Path(dest).write_text("\n".join(L) + "\n", encoding="utf-8")
    print("wrote", dest)
    print("  1 paper, %d questions, %d assets" % (len(rows), len(plan)))


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("outdir")
    ap.add_argument("dest")
    ap.add_argument("--school", default="RI")
    ap.add_argument("--year", type=int, default=2024)
    ap.add_argument("--paper", type=int, default=2)
    ap.add_argument("--level", default="H2")
    ap.add_argument("--assessment", default="prelim")
    ap.add_argument("--skip-assets", type=lambda s: s.lower() != "false",
                    default=True, metavar="{true,false}",
                    help="default true: omit question_assets even if "
                         "asset_plan.json has rows, because a hand-cropped "
                         "paper's plan can exist before the images do. Pass "
                         "--skip-assets=false once the crops are uploaded.")
    a = ap.parse_args()
    main(a.outdir, a.dest, school=a.school, year=a.year,
        paper=a.paper, level=a.level, assessment=a.assessment,
        skip_assets=a.skip_assets)
