#!/usr/bin/env python3
"""Emit the RI 2024 H2 P2 worked-solutions migration.

Conventions enforced here come from the handoff's hard-won list:
  SS8  question_assets has NO unique constraint and ON CONFLICT is unavailable,
       so a re-run silently duplicates -> explicit RAISE EXCEPTION pre-flight.
  SS11 RETURNING on every live UPDATE; scope by id, never by predicate;
       dollar-quote HTML; dry run ends in ROLLBACK for the user to flip.
  SS9  confirm with a SEPARATE SELECT, never by re-reading the validation block.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

QUESTION_IDS = {
    1: "8dafc8c0-7446-4027-80d2-c7d4a1149efd",
    2: "599e83cc-ad19-4637-9df4-cb09cf36388f",
    3: "46e0560d-2531-4e28-a73e-16fc8116f909",
    4: "fcc49f25-f5eb-46f8-b09f-eb0847865458",
}
PAPER_ID = "cd77eea4-d0b5-46ee-a561-50ad38eddec8"
TAG = "$ws$"


def main(outdir: str, dest: str):
    out_p = Path(outdir)
    sols = json.loads((out_p / "worked_solutions.json").read_text(encoding="utf-8"))
    plan = json.loads((out_p / "asset_plan.json").read_text(encoding="utf-8"))

    for q, html in sols.items():
        # The delimiter itself must not occur in the body, or the quote ends
        # early. "ws-fig" is not "$ws$" -- test the actual tag.
        if TAG in html:
            raise SystemExit("dollar-quote tag %s occurs inside Q%s content; "
                             "choose another tag" % (TAG, q))

    L = []
    add = L.append
    add("-- RI 2024 H2 Chemistry Prelims Paper 2 -- worked solutions + answer figures")
    add("-- Generated by gen_migration.py. DRY RUN: ends in ROLLBACK.")
    add("-- Flip the final ROLLBACK to COMMIT once the output looks right,")
    add("-- then confirm with the SEPARATE verification SELECT at the bottom.")
    add("")
    add("BEGIN;")
    add("")
    add("-- ---------------------------------------------------------------")
    add("-- PRE-FLIGHT. question_assets has no unique constraint, so a second")
    add("-- run would silently duplicate every figure rather than erroring.")
    add("-- ---------------------------------------------------------------")
    add("DO $preflight$")
    add("DECLARE n int;")
    add("BEGIN")
    add("  -- 1. the four questions exist and belong to this paper")
    add("  SELECT count(*) INTO n FROM questions")
    add("   WHERE id IN (%s)" % ", ".join("'%s'" % v for v in QUESTION_IDS.values()))
    add("     AND paper_id = '%s';" % PAPER_ID)
    add("  IF n <> 4 THEN")
    add("    RAISE EXCEPTION 'expected 4 RI P2 questions, found %', n;")
    add("  END IF;")
    add("")
    add("  -- 2. no worked solutions already present (this would overwrite)")
    add("  SELECT count(*) INTO n FROM questions")
    add("   WHERE paper_id = '%s' AND worked_solution IS NOT NULL;" % PAPER_ID)
    add("  IF n <> 0 THEN")
    add("    RAISE EXCEPTION 'RI P2 already has % worked solution(s) -- "
        "re-running would overwrite them', n;")
    add("  END IF;")
    add("")
    add("  -- 3. no answer-side assets yet (the duplicate-on-rerun trap)")
    add("  SELECT count(*) INTO n FROM question_assets a")
    add("    JOIN questions q ON q.id = a.question_id")
    add("   WHERE q.paper_id = '%s' AND a.slot LIKE 'ans-%%';" % PAPER_ID)
    add("  IF n <> 0 THEN")
    add("    RAISE EXCEPTION 'RI P2 already has % ans- asset(s) -- "
        "re-running would duplicate them', n;")
    add("  END IF;")
    add("")
    add("  -- 4. the ordinals we are about to use are genuinely free")
    for q, qid in QUESTION_IDS.items():
        ords = sorted(i["ordinal"] for i in plan if i["question"] == q)
        if not ords:
            continue
        add("  SELECT count(*) INTO n FROM question_assets")
        add("   WHERE question_id = '%s' AND ordinal IN (%s);"
            % (qid, ", ".join(str(o) for o in ords)))
        add("  IF n <> 0 THEN")
        add("    RAISE EXCEPTION 'Q%d: %% of the ordinals %s are already taken', n;"
            % (q, ords))
        add("  END IF;")
    add("END")
    add("$preflight$;")
    add("")
    add("-- ---------------------------------------------------------------")
    add("-- worked_solution, scoped by id (SS11), RETURNING to show the effect")
    add("-- ---------------------------------------------------------------")
    for q in sorted(sols, key=int):
        qid = QUESTION_IDS[int(q)]
        add("UPDATE questions SET worked_solution = %s%s%s"
            % (TAG, sols[q], TAG))
        add(" WHERE id = '%s'" % qid)
        add(" RETURNING id, question_number, length(worked_solution) AS ws_chars;")
        add("")
    add("-- ---------------------------------------------------------------")
    add("-- answer-side assets. slot is prefixed 'ans-' so the frontend's")
    add("-- isAnswerSlot = /^(ans|sol)[-_]/i withholds them until reveal.")
    add("-- storage_path is a BARE FILENAME: bucket is question-assets (SS8).")
    add("-- ordinal continues each question's existing sequence.")
    add("-- ---------------------------------------------------------------")
    add("INSERT INTO question_assets (question_id, slot, storage_path, ordinal)")
    add("VALUES")
    rows = []
    for item in sorted(plan, key=lambda i: (i["question"], i["ordinal"])):
        rows.append("  ('%s', '%s', '%s', %d)"
                    % (QUESTION_IDS[item["question"]], item["slot"],
                       item["storage_path"], item["ordinal"]))
    add(",\n".join(rows))
    add("RETURNING question_id, slot, storage_path, ordinal;")
    add("")
    add("-- Flip to COMMIT when the above looks right.")
    add("ROLLBACK;")
    add("")
    add("-- ---------------------------------------------------------------")
    add("-- VERIFICATION -- run SEPARATELY, after COMMIT (SS9: never confirm a")
    add("-- commit by re-reading the validation block).")
    add("-- ---------------------------------------------------------------")
    add("-- select q.question_number,")
    add("--        length(q.worked_solution)                    as ws_chars,")
    add("--        count(a.id) filter (where a.slot like 'ans-%') as ans_assets,")
    add("--        min(a.ordinal) filter (where a.slot like 'ans-%') as first_ord,")
    add("--        max(a.ordinal) filter (where a.slot like 'ans-%') as last_ord")
    add("--   from questions q")
    add("--   left join question_assets a on a.question_id = q.id")
    add("--  where q.paper_id = '%s'" % PAPER_ID)
    add("--  group by q.question_number, q.worked_solution")
    add("--  order by q.question_number;")
    add("-- Expect: Q1 3 assets ord 5-7 | Q2 0 | Q3 8 ord 10-17 | Q4 3 ord 3-5")

    Path(dest).write_text("\n".join(L) + "\n", encoding="utf-8")
    print("wrote", dest)
    print("  %d UPDATEs, %d asset rows" % (len(sols), len(rows)))


if __name__ == "__main__":
    main(*sys.argv[1:3])
