#!/usr/bin/env python3
"""Emit UPDATEs for a STRUCTURED paper's questions whose markup changed after
the paper went live -- the flow/table-shape sibling of `gen_patch_migration.py`
(which is hardcoded to `q.type = 'mcq'` and an `options` jsonb column that
structured questions don't have).

Built for EJC 2024 H2 P2's post-live formatting review (2026-09-26): eight
rendering defects (see `claude/ejc-2024-h2-p2-ingest-notes.md`, "Formatting
review round") were found and fixed in `ingest/` AFTER Q1-Q4 were already
committed with `gen_parts_migration.py`'s original `content_html`/
`content_text` -- so the fix lives in code, but the four already-live rows
still hold the OLD, buggy strings until a migration like this one runs.

SCOPING (handoff SS11: "scope UPDATEs by id, not predicate")
------------------------------------------------------------
Same reasoning as `gen_patch_migration.py`: the ids are server-generated
`gen_random_uuid()` values this generator has never seen, so the predicate
used instead is as tight as the id would be -- paper (school, year,
paper_number, level) plus question_number plus `type = 'structured'` -- and a
pre-flight asserts it matches EXACTLY one row per question before anything is
written.

IDEMPOTENT BY CONSTRUCTION, unlike the asset-filename fix
----------------------------------------------------------
`gen_parts_assets_fix_migration.py`'s pre-flight has to check the CURRENT
value equals the OLD one, because a rename applied twice with mismatched
pairs would corrupt the row silently (old_path/new_path is a pair, not a
value). A markup patch has no such hazard: content_html/content_text are set
to their new, correct value outright, so running this file twice (or after
some OTHER unrelated column change) just sets the same value twice -- safe,
not merely tolerated. The pre-flight below therefore only needs to confirm
each targeted question exists exactly once, not what it currently contains.

`content_text` is updated alongside `content_html` whenever it changed:
content_search is generated from content_text, so patching only the markup
leaves search reflecting the old wording (handoff SS6D; `gen_patch_migration.py`
makes the identical point).

ASSETS
------
Each patched question's question_assets rows are RESYNCED: deleted, then
re-inserted from the CURRENT `asset_plan.json` -- not an optimisation, a
correctness one (`gen_patch_migration.py`'s own module note explains why:
question_assets has no unique constraint, so delete-then-insert is the only
way to make the rows match the plan exactly). A question in `qnums` with no
rows in the plan is therefore emptied, which is intended.

Usage:
  python3 -m ingest.gen_parts_patch_migration <outdir> <qnums> <dest.sql> \\
      [--school EJC --year 2024 --paper 2 --level H2]

<qnums> is a comma-separated list, e.g. "1,2,3,4". <outdir> must contain
questions.json (freshly re-extracted, ALREADY VERIFIED against a clean
extract_parts.py run) and asset_plan.json.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

TAG = "$qp$"


def _lit(s: str) -> str:
    if TAG in s:
        raise SystemExit("dollar-quote tag %s occurs inside a value" % TAG)
    return TAG + s + TAG


def main(outdir: str, qnums: str, dest: str, *,
        school: str = "EJC", year: int = 2024, paper: int = 2, level: str = "H2"):
    SCHOOL, YEAR, PAPER, LEVEL = school, year, paper, level
    rows = {r["question_number"]: r for r in json.loads(
        (Path(outdir) / "questions.json").read_text(encoding="utf-8"))}
    plan = json.loads(
        (Path(outdir) / "asset_plan.json").read_text(encoding="utf-8"))
    want = [int(x) for x in qnums.split(",") if x.strip()]
    missing = [q for q in want if q not in rows]
    if missing:
        raise SystemExit("no extracted row for questions %s" % missing)

    where = ("p.school = '%s' AND p.year = %d AND p.paper_number = %d "
             "AND p.level = '%s'" % (SCHOOL, YEAR, PAPER, LEVEL))

    L: list = []
    add = L.append
    add("-- %s %d %s P%d -- markup patch for question(s) %s"
        % (SCHOOL, YEAR, LEVEL, PAPER, ", ".join(str(q) for q in want)))
    add("-- Generated by gen_parts_patch_migration.py. DRY RUN: ends in ROLLBACK.")
    add("-- Flip ROLLBACK to COMMIT once the output looks right, then confirm")
    add("-- with the SEPARATE verification SELECT at the bottom.")
    add("")
    add("BEGIN;")
    add("")
    add("DO $preflight$")
    add("DECLARE n int;")
    add("BEGIN")
    add("  SELECT count(*) INTO n FROM questions q JOIN papers p ON p.id = q.paper_id")
    add("   WHERE %s AND q.type = 'structured'" % where)
    add("     AND q.question_number IN (%s);" % ", ".join(str(q) for q in want))
    add("  IF n <> %d THEN" % len(want))
    add("    RAISE EXCEPTION 'expected %d question(s) to patch, matched %%', n;"
        % len(want))
    add("  END IF;")
    add("END")
    add("$preflight$;")
    add("")
    for q in want:
        r = rows[q]
        add("UPDATE questions q SET content_html = %s,"
            % _lit(r["content_html"]))
        add("                       content_text = %s" % _lit(r["content_text"]))
        add("  FROM papers p")
        add(" WHERE p.id = q.paper_id AND %s" % where)
        add("   AND q.type = 'structured' AND q.question_number = %d" % q)
        add(" RETURNING q.question_number, length(q.content_html) AS html_chars,")
        add("           q.content_search IS NOT NULL AS searchable;")
        add("")

    qsel = ("SELECT q.id FROM questions q JOIN papers p ON p.id = q.paper_id\n"
            "         WHERE %s AND q.type = 'structured'\n"
            "           AND q.question_number IN (%s)"
            % (where, ", ".join(str(q) for q in want)))
    add("-- Resync the asset rows for these questions -- see the module note.")
    add("DELETE FROM question_assets WHERE question_id IN (")
    add("  " + qsel.replace("\n", "\n  "))
    add(");")
    add("")
    arows = [a for a in plan if a["question"] in set(want)]
    if arows:
        add("INSERT INTO question_assets (question_id, slot, storage_path, ordinal)")
        add("SELECT q.id, a.slot, a.path, a.ord")
        add("  FROM questions q JOIN papers p ON p.id = q.paper_id")
        add("  JOIN (VALUES")
        add(",\n".join(
            "    (%d, %s, %s, %d)" % (a["question"], _lit(a["slot"]),
                                      _lit(a["storage_path"]), a["ordinal"])
            for a in sorted(arows, key=lambda a: (a["question"], a["ordinal"]))))
        add("  ) AS a(qn, slot, path, ord) ON a.qn = q.question_number")
        add(" WHERE %s AND q.type = 'structured'" % where)
        add("RETURNING question_id, slot, storage_path, ordinal;")
        add("-- Expect %d asset row(s) returned." % len(arows))
    else:
        add("-- No assets planned for any patched question: the DELETE is all.")
    add("")
    add("-- Flip to COMMIT when the above looks right.")
    add("ROLLBACK;")
    add("")
    add("-- VERIFICATION -- run SEPARATELY, after COMMIT:")
    add("-- select q.question_number, length(q.content_html) as html_chars,")
    add("--        q.content_search is not null as searchable,")
    add("--        count(a.id) as assets,")
    add("--        string_agg(a.slot, ',' order by a.ordinal) as slots")
    add("--   from questions q join papers p on p.id = q.paper_id")
    add("--   left join question_assets a on a.question_id = q.id")
    add("--  where %s and q.question_number in (%s)"
        % (where, ", ".join(str(q) for q in want)))
    add("--  group by q.question_number, q.content_html, q.content_search")
    add("--  order by q.question_number;")

    bad = [l for l in L if "%%" in l]
    if bad:
        raise SystemExit("emitted SQL contains a literal %%%%:\n  " + "\n  ".join(bad))
    Path(dest).write_text("\n".join(L) + "\n", encoding="utf-8")
    print("wrote", dest)
    print("  %d question(s) patched" % len(want))


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("outdir")
    ap.add_argument("qnums")
    ap.add_argument("dest")
    ap.add_argument("--school", default="EJC")
    ap.add_argument("--year", type=int, default=2024)
    ap.add_argument("--paper", type=int, default=2)
    ap.add_argument("--level", default="H2")
    a = ap.parse_args()
    main(a.outdir, a.qnums, a.dest,
        school=a.school, year=a.year, paper=a.paper, level=a.level)
