#!/usr/bin/env python3
"""Attach QUESTION-SIDE assets to a structured paper whose paper + questions
are ALREADY LIVE (loaded earlier by `gen_parts_migration.py --skip-assets`,
the default, before the diagrams were cropped/uploaded).

Why this is a SEPARATE script, not `gen_parts_migration.py --skip-assets=false`
re-run against the same outdir: that re-run ALSO re-emits the paper +
questions INSERT. The pre-flight guard correctly refuses once the paper is
already loaded (`RAISE EXCEPTION '... is already loaded'`) -- so it fails
SAFE, but it also does not do the one thing actually wanted at this point:
attach assets to the rows that already exist. This script only touches
`question_assets`, and finds the target `question_id`s by a paper-identity
JOIN (school/year/paper_number/level -> question_number) rather than by
hardcoded UUIDs -- same convention as `gen_parts_migration.py` itself and
`gen_parts_patch_migration.py`/`gen_parts_tag_migration.py`, and the
JOIN-not-hardcoded approach `gen_parts_answers_migration.py` (P3's
worked-solution attacher) was rebuilt to use, rather than a fifth
hardcoded-ids copy in the style of the original `gen_migration.py`.

Guards (handoff SS8/SS11 -- `question_assets` has NO unique constraint, so
`ON CONFLICT` is unavailable and a re-run silently duplicates):
  1. the paper exists exactly once (by school/year/paper_number/level).
  2. every question_number the plan targets exists exactly once under it.
  3. none of the target ordinals are already taken for that question -- the
     actual re-run trap, checked per-question since ordinal is per-question.

Usage:
  python3 -m ingest.gen_parts_assets_migration <outdir> <dest.sql> \\
      [--school EJC --year 2024 --paper 2 --level H2]

<outdir> need only contain `asset_plan.json` -- `questions.json` is not
read, since the questions already exist and are not being re-inserted.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

TAG = "$qh$"


def _lit(s: str) -> str:
    """Dollar-quote a value, having checked the delimiter is not inside it.

    Handoff SS11: test for the ACTUAL tag, not a substring of it.
    """
    if TAG in s:
        raise SystemExit("dollar-quote tag %s occurs inside a value" % TAG)
    return TAG + s + TAG


def main(outdir: str, dest: str, *,
        school: str = "RI", year: int = 2024, paper: int = 2, level: str = "H2"):
    SCHOOL, YEAR, PAPER, LEVEL = school, year, paper, level
    out = Path(outdir)
    plan = json.loads((out / "asset_plan.json").read_text(encoding="utf-8"))
    if not plan:
        raise SystemExit("asset_plan.json has no rows -- nothing to attach")

    qnums = sorted({a["question"] for a in plan})

    L: list = []
    add = L.append
    add("-- %s %d %s Paper %d -- attach %d question-side asset(s) to the "
        "ALREADY-LIVE paper" % (SCHOOL, YEAR, LEVEL, PAPER, len(plan)))
    add("-- Generated by gen_parts_assets_migration.py. DRY RUN: ends in ROLLBACK.")
    add("-- Flip ROLLBACK to COMMIT once the output looks right, then confirm")
    add("-- with the SEPARATE verification SELECT at the bottom (SS9: a dry run")
    add("-- and a real commit print identical output).")
    add("")
    add("BEGIN;")
    add("")
    add("-- ---------------------------------------------------------------")
    add("-- PRE-FLIGHT. question_assets has NO unique constraint, so a second")
    add("-- run would silently duplicate every row rather than erroring.")
    add("-- ---------------------------------------------------------------")
    add("DO $preflight$")
    add("DECLARE n int;")
    add("BEGIN")
    add("  -- 1. this exact paper exists exactly once")
    add("  SELECT count(*) INTO n FROM papers")
    add("   WHERE school = %s AND year = %d AND paper_number = %d"
        % (_lit(SCHOOL), YEAR, PAPER))
    add("     AND level = '%s';" % LEVEL)
    add("  IF n <> 1 THEN")
    add("    RAISE EXCEPTION 'expected exactly 1 %s %d %s P%d paper, found %%', n;"
        % (SCHOOL, YEAR, LEVEL, PAPER))
    add("  END IF;")
    add("")
    add("  -- 2. every question number this plan targets exists exactly once")
    add("  --    under that paper")
    add("  SELECT count(*) INTO n FROM questions q")
    add("    JOIN papers p ON p.id = q.paper_id")
    add("   WHERE p.school = %s AND p.year = %d AND p.paper_number = %d"
        % (_lit(SCHOOL), YEAR, PAPER))
    add("     AND p.level = '%s' AND q.question_number IN (%s);"
        % (LEVEL, ", ".join(str(q) for q in qnums)))
    add("  IF n <> %d THEN" % len(qnums))
    add("    RAISE EXCEPTION 'expected %d questions (%s) under %s %d %s P%d, "
        "found %%', n;"
        % (len(qnums), ", ".join(str(q) for q in qnums),
           SCHOOL, YEAR, LEVEL, PAPER))
    add("  END IF;")
    add("")
    add("  -- 3. the ordinals we are about to use are genuinely free, per")
    add("  --    question (ordinal is 1-based and PER-QUESTION, not global)")
    for q in qnums:
        ords = sorted(a["ordinal"] for a in plan if a["question"] == q)
        add("  SELECT count(*) INTO n FROM question_assets a")
        add("    JOIN questions q2 ON q2.id = a.question_id")
        add("    JOIN papers p2 ON p2.id = q2.paper_id")
        add("   WHERE p2.school = %s AND p2.year = %d AND p2.paper_number = %d"
            % (_lit(SCHOOL), YEAR, PAPER))
        add("     AND p2.level = '%s' AND q2.question_number = %d"
            % (LEVEL, q))
        add("     AND a.ordinal IN (%s);" % ", ".join(str(o) for o in ords))
        add("  IF n <> 0 THEN")
        add("    RAISE EXCEPTION 'Q%d: %% of the ordinals %s are already taken', n;"
            % (q, ords))
        add("  END IF;")
    add("END")
    add("$preflight$;")
    add("")
    add("-- ---------------------------------------------------------------")
    add("-- INSERT, scoped to the live paper/questions by identity join --")
    add("-- never by a bare question_number, which is only unique per paper.")
    add("-- storage_path is a BARE FILENAME: bucket is question-assets.")
    add("-- ---------------------------------------------------------------")
    add("INSERT INTO question_assets (question_id, slot, storage_path, ordinal)")
    add("SELECT q.id, a.slot, a.path, a.ord")
    add("  FROM questions q")
    add("  JOIN papers p ON p.id = q.paper_id")
    add("  JOIN (VALUES")
    arows = []
    for a in sorted(plan, key=lambda a: (a["question"], a["ordinal"])):
        arows.append("    (%d, %s, %s, %d)"
                     % (a["question"], _lit(a["slot"]),
                        _lit(a["storage_path"]), a["ordinal"]))
    add(",\n".join(arows))
    add("  ) AS a(qn, slot, path, ord) ON a.qn = q.question_number")
    add(" WHERE p.school = %s AND p.year = %d AND p.paper_number = %d"
        % (_lit(SCHOOL), YEAR, PAPER))
    add("   AND p.level = '%s'" % LEVEL)
    add("RETURNING question_id, slot, storage_path, ordinal;")
    add("")
    add("-- Expect %d asset rows returned." % len(plan))
    add("")
    add("-- Flip to COMMIT when the above looks right.")
    add("ROLLBACK;")
    add("")
    add("-- ---------------------------------------------------------------")
    add("-- VERIFICATION -- run SEPARATELY, after COMMIT (SS9: never confirm a")
    add("-- commit by re-reading the dry-run output above).")
    add("-- ---------------------------------------------------------------")
    add("-- select q.question_number,")
    add("--        count(a.id)                               as assets,")
    add("--        string_agg(a.slot, ',' order by a.ordinal)  as slots")
    add("--   from questions q")
    add("--   join papers p on p.id = q.paper_id")
    add("--   left join question_assets a on a.question_id = q.id")
    add("--  where p.school = '%s' and p.year = %d" % (SCHOOL, YEAR))
    add("--    and p.paper_number = %d and p.level = '%s'" % (PAPER, LEVEL))
    add("--  group by q.question_number")
    add("--  order by q.question_number;")
    add("-- Expect %d rows, %d assets in total, matching asset_plan.json."
        % (len(qnums), len(plan)))

    bad = [l for l in L if "%%" in l]
    if bad:
        raise SystemExit("emitted SQL contains a literal %%%% -- see "
                         "gen_tag_migration.py:\n  " + "\n  ".join(bad))
    Path(dest).write_text("\n".join(L) + "\n", encoding="utf-8")
    print("wrote", dest)
    print("  %d questions, %d assets" % (len(qnums), len(plan)))


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("outdir")
    ap.add_argument("dest")
    ap.add_argument("--school", default="RI")
    ap.add_argument("--year", type=int, default=2024)
    ap.add_argument("--paper", type=int, default=2)
    ap.add_argument("--level", default="H2")
    a = ap.parse_args()
    main(a.outdir, a.dest, school=a.school, year=a.year,
        paper=a.paper, level=a.level)
