#!/usr/bin/env python3
"""Correct `storage_path` on already-committed `question_assets` rows.

For when the paper's assets migration already ran with the WRONG filenames
(e.g. the generator's own naming convention, rather than whatever the user
actually saved the crops as) -- a targeted UPDATE, not a re-run of the
INSERT (which the pre-flight would refuse anyway; see
`gen_parts_assets_migration.py`'s own module docstring for that failure
mode, hit and fixed on EJC 2024 H2 P2, 2026-09-26).

Scoped by (question_id, slot) -- both already known and immutable once the
asset row exists -- never by storage_path itself (that's the very column
being changed) and never by a bare predicate alone (handoff SS11).

The pre-flight is the real safety net here: it requires each target row to
CURRENTLY hold the OLD value given, so
  (a) a typo in `old_path` is caught before anything is touched (found 0,
      not 9), and
  (b) running this twice is a no-op-then-refusal, not a silent double
      rename -- the second run finds the rows already carrying `new_path`,
      not `old_path`, and refuses.

Usage:
  python3 -m ingest.gen_parts_assets_fix_migration <renames.json> <dest.sql>

<renames.json>: a list of
  {"question_id": "...", "slot": "...", "old_path": "...", "new_path": "..."}
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

TAG = "$qh$"


def _lit(s: str) -> str:
    if TAG in s:
        raise SystemExit("dollar-quote tag %s occurs inside a value" % TAG)
    return TAG + s + TAG


def main(renames_file: str, dest: str):
    renames = json.loads(Path(renames_file).read_text(encoding="utf-8"))
    if not renames:
        raise SystemExit("no renames given")

    L: list = []
    add = L.append
    add("-- Correct storage_path on %d already-committed question_assets row(s)"
        % len(renames))
    add("-- Generated by gen_parts_assets_fix_migration.py. DRY RUN: ends in ROLLBACK.")
    add("-- Flip ROLLBACK to COMMIT once the output looks right, then confirm")
    add("-- with the SEPARATE verification SELECT at the bottom.")
    add("")
    add("BEGIN;")
    add("")
    add("-- ---------------------------------------------------------------")
    add("-- PRE-FLIGHT. Every target row must currently hold the OLD path --")
    add("-- catches a typo'd old_path (found 0) and makes a second run of")
    add("-- this same file refuse instead of silently no-op-renaming twice.")
    add("-- ---------------------------------------------------------------")
    add("DO $preflight$")
    add("DECLARE n int;")
    add("BEGIN")
    add("  SELECT count(*) INTO n FROM question_assets a")
    add("   WHERE (a.question_id, a.slot, a.storage_path) IN (")
    add(",\n".join(
        "    ('%s', %s, %s)" % (r["question_id"], _lit(r["slot"]), _lit(r["old_path"]))
        for r in renames))
    add("  );")
    add("  IF n <> %d THEN" % len(renames))
    add("    RAISE EXCEPTION 'expected %d row(s) still holding their OLD "
        "storage_path, found %%', n;" % len(renames))
    add("  END IF;")
    add("END")
    add("$preflight$;")
    add("")
    add("-- ---------------------------------------------------------------")
    add("-- UPDATE, scoped by (question_id, slot) -- both fixed and already")
    add("-- known, never by the storage_path column being changed itself.")
    add("-- ---------------------------------------------------------------")
    add("UPDATE question_assets a SET storage_path = v.new_path")
    add("  FROM (VALUES")
    add(",\n".join(
        "    ('%s'::uuid, %s, %s)" % (r["question_id"], _lit(r["slot"]),
                                      _lit(r["new_path"]))
        for r in renames))
    add("  ) AS v(qid, slot, new_path)")
    add(" WHERE a.question_id = v.qid AND a.slot = v.slot")
    add("RETURNING a.question_id, a.slot, a.storage_path, a.ordinal;")
    add("")
    add("-- Expect %d row(s) returned, storage_path showing the NEW names." % len(renames))
    add("")
    add("-- Flip to COMMIT when the above looks right.")
    add("ROLLBACK;")
    add("")
    add("-- ---------------------------------------------------------------")
    add("-- VERIFICATION -- run SEPARATELY, after COMMIT.")
    add("-- ---------------------------------------------------------------")
    add("-- select question_id, slot, storage_path, ordinal")
    add("--   from question_assets")
    add("--  where (question_id, slot) IN (")
    add(",\n".join(
        "--    ('%s', %s)" % (r["question_id"], _lit(r["slot"])) for r in renames))
    add("--  )")
    add("--  order by question_id, ordinal;")
    add("-- Expect %d rows, storage_path matching the NEW names exactly." % len(renames))

    bad = [l for l in L if "%%" in l]
    if bad:
        raise SystemExit("emitted SQL contains a literal %%%% :\n  " + "\n  ".join(bad))
    Path(dest).write_text("\n".join(L) + "\n", encoding="utf-8")
    print("wrote", dest)
    print("  %d row(s) to correct" % len(renames))


if __name__ == "__main__":
    main(*sys.argv[1:3])
