#!/usr/bin/env python3
"""Emit a structured paper's answer-scheme migration:
  - worked_solution UPDATE for each question that has one
  - an ADDITIVE-ONLY INSERT into question_assets for the answer figures

Mirrors ingest/gen_parts_patch_migration.py's house conventions (dollar
quoting, DO $preflight$ guard, UPDATE...FROM papers...RETURNING, ROLLBACK
dry run, trailing verification SELECT, no literal %%), with two differences
specific to this migration:

1. worked_solution is a NEW value being SET for the first time on these rows
   (they currently hold NULL / empty) -- idempotent by construction, same as
   the content_html patch precedent.
2. question_assets is INSERT-ONLY, not a delete+resync: a structured
   question already has LIVE stem-figure asset rows from the question-side
   ingest, and a resync (DELETE then re-INSERT) would wrongly wipe those.
   Since the table has no unique constraint, running an additive INSERT
   twice would duplicate rows -- so the preflight additionally asserts NONE
   of the target (question_number, slot) pairs already exist before
   inserting, and ordinal is computed per-question as (current MAX ordinal)
   + a fixed within-question offset supplied in the assets file, so the new
   rows always sort after whatever stem-figure assets are already there.

Generalised from the EJC 2024 H2 P2 one-off script (2026-09-26) into a
reusable, CLI-parameterised generator, matching the house pattern every
other gen_*_migration.py already follows -- see HANDOFF.md's own note on
why a script meant to be reused across papers should never stay hardcoded
to the one paper it was first built for.

Usage:
  python3 -m ingest.gen_answers_migration <worked_solutions.json> \\
      <answer_assets.json> <dest.sql> \\
      [--school EJC] [--year 2024] [--paper 2] [--level H2]

`worked_solutions.json`: {"1": "<div class=\\"worked-solution\\">...</div>", ...}
  -- question number (as a string key) -> the full worked_solution HTML.
  Every key becomes an UPDATE; a question with no worked solution yet simply
  has no key.

`answer_assets.json`: a list of
  {"question": 1, "slot": "ans-cv", "path": "SCHOOL_LEVEL_PAPER_Q1_ans-cv_YEAR.png",
   "offset": 1}
  -- one entry per answer-figure asset, in the user's OWN chosen filenames
  (never invent a filename here -- see HANDOFF.md's standing rule: the user
  snips and names the figure, this script only matches their name). `offset`
  is the within-question ordinal offset applied on top of that question's
  current MAX(ordinal), so entries for the same question should number their
  offsets 1, 2, 3... in the order they should sort after the existing
  stem-figure assets.
"""
from __future__ import annotations
import argparse
import json
from pathlib import Path

TAG = "$qp$"


def _lit(s: str) -> str:
    if TAG in s:
        raise SystemExit("dollar-quote tag %s occurs inside a value" % TAG)
    return TAG + s + TAG


def main(ws_json: str, assets_json: str, dest: str, *, school: str = "RI",
        year: int = 2024, paper: int = 2, level: str = "H2"):
    worked = json.loads(Path(ws_json).read_text(encoding="utf-8"))
    assets_raw = json.loads(Path(assets_json).read_text(encoding="utf-8"))
    ASSETS = [(a["question"], a["slot"], a["path"], a["offset"])
             for a in assets_raw]
    QNUMS = sorted(int(q) for q in worked.keys())

    WHERE = ("p.school = '%s' AND p.year = %d AND p.paper_number = %d "
             "AND p.level = '%s'" % (school, year, paper, level))

    L: list = []
    add = L.append

    add("-- %s %d %s P%d -- answer-scheme migration (worked_solution + %d answer figures)"
        % (school, year, level, paper, len(ASSETS)))
    add("-- Generated by gen_answers_migration.py. DRY RUN: ends in ROLLBACK.")
    add("-- Flip ROLLBACK to COMMIT once the output looks right, then confirm")
    add("-- with the SEPARATE verification SELECT at the bottom.")
    add("")
    add("BEGIN;")
    add("")
    add("DO $preflight$")
    add("DECLARE n int;")
    add("BEGIN")
    add("  -- exactly one structured question row per question number")
    add("  SELECT count(*) INTO n FROM questions q JOIN papers p ON p.id = q.paper_id")
    add("   WHERE %s AND q.type = 'structured'" % WHERE)
    add("     AND q.question_number IN (%s);" % ", ".join(str(q) for q in QNUMS))
    add("  IF n <> %d THEN" % len(QNUMS))
    add("    RAISE EXCEPTION 'expected %d question(s), matched %%', n;" % len(QNUMS))
    add("  END IF;")
    add("")
    if ASSETS:
        add("  -- additive-only insert below must never run twice: none of the")
        add("  -- (question_number, slot) pairs may already exist")
        add("  SELECT count(*) INTO n FROM question_assets a")
        add("    JOIN questions q ON q.id = a.question_id")
        add("    JOIN papers p ON p.id = q.paper_id")
        add("   WHERE %s" % WHERE)
        add("     AND (q.question_number, a.slot) IN (")
        add(",\n".join("       (%d, %s)" % (qn, _lit(slot))
                       for qn, slot, _, _ in ASSETS))
        add("     );")
        add("  IF n <> 0 THEN")
        add("    RAISE EXCEPTION 'expected no existing ans-* rows for these (question, slot) pairs, found %', n;")
        add("  END IF;")
    add("END")
    add("$preflight$;")
    add("")

    for q in QNUMS:
        html = worked[str(q)]
        add("UPDATE questions q SET worked_solution = %s" % _lit(html))
        add("  FROM papers p")
        add(" WHERE p.id = q.paper_id AND %s" % WHERE)
        add("   AND q.type = 'structured' AND q.question_number = %d" % q)
        add(" RETURNING q.question_number, length(q.worked_solution) AS html_chars;")
        add("")

    if ASSETS:
        add("-- Additive insert: %d new answer-figure asset rows, ordinal placed" % len(ASSETS))
        add("-- AFTER whatever stem-figure assets already exist for each question")
        add("-- (base = current MAX(ordinal) per question; offset keeps this batch's")
        add("-- own relative order stable within that question).")
        add("INSERT INTO question_assets (question_id, slot, storage_path, ordinal)")
        add("SELECT q.id, a.slot, a.path, base.next_ord + a.off")
        add("  FROM questions q JOIN papers p ON p.id = q.paper_id")
        add("  JOIN (VALUES")
        add(",\n".join(
            "    (%d, %s, %s, %d)" % (qn, _lit(slot), _lit(path), off)
            for qn, slot, path, off in ASSETS))
        add("  ) AS a(qn, slot, path, off) ON a.qn = q.question_number")
        add("  JOIN LATERAL (")
        add("    SELECT COALESCE(MAX(qa.ordinal), 0) AS next_ord")
        add("      FROM question_assets qa WHERE qa.question_id = q.id")
        add("  ) base ON true")
        add(" WHERE %s AND q.type = 'structured'" % WHERE)
        add("RETURNING question_id, slot, storage_path, ordinal;")
        add("-- Expect %d asset row(s) returned." % len(ASSETS))
        add("")
    add("-- Flip to COMMIT when the above looks right.")
    add("ROLLBACK;")
    add("")
    add("-- VERIFICATION -- run SEPARATELY, after COMMIT:")
    add("-- select q.question_number, length(q.worked_solution) as ws_chars,")
    add("--        count(a.id) filter (where a.slot like 'ans-%') as ans_assets,")
    add("--        string_agg(a.slot, ',' order by a.ordinal)")
    add("--          filter (where a.slot like 'ans-%') as ans_slots")
    add("--   from questions q join papers p on p.id = q.paper_id")
    add("--   left join question_assets a on a.question_id = q.id")
    add("--  where %s and q.question_number in (%s)"
        % (WHERE, ", ".join(str(q) for q in QNUMS)))
    add("--  group by q.question_number, q.worked_solution")
    add("--  order by q.question_number;")

    bad = [l for l in L if "%%" in l]
    bad = [l for l in bad if "RAISE EXCEPTION" not in l]
    if bad:
        raise SystemExit("emitted SQL contains an unexpected literal %%%%:\n  "
                         + "\n  ".join(bad))

    Path(dest).write_text("\n".join(L) + "\n", encoding="utf-8")
    print("wrote", dest)
    print("  %d question(s) updated, %d asset row(s) planned" % (len(QNUMS), len(ASSETS)))


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("ws_json", help="worked_solutions.json: {qnum: html}")
    ap.add_argument("assets_json",
                    help="[{question, slot, path, offset}, ...] -- offset "
                         "is the within-question ordinal offset on top of "
                         "that question's current MAX(ordinal)")
    ap.add_argument("dest")
    ap.add_argument("--school", default="RI")
    ap.add_argument("--year", type=int, default=2024)
    ap.add_argument("--paper", type=int, default=2)
    ap.add_argument("--level", default="H2")
    a = ap.parse_args()
    main(a.ws_json, a.assets_json, a.dest, school=a.school, year=a.year,
        paper=a.paper, level=a.level)
