#!/usr/bin/env python3
"""Emit UPDATEs for questions whose markup changed after the paper went live.

Once the content migration has been committed the insert cannot be re-run --
its pre-flight refuses, correctly, because a second run would duplicate the
paper. Fixes therefore arrive as scoped UPDATEs.

SCOPING (handoff SS11: "scope UPDATEs by id, not predicate")
------------------------------------------------------------
The ids are generated server-side by gen_random_uuid(), so a generator that has
never seen the live database does not have them. The predicate used instead is
as tight as the id would be -- paper (school, year, paper_number, LEVEL) plus
question_number plus type='mcq' -- and a pre-flight asserts it matches EXACTLY
one row per question before anything is written. That is what the id rule is
protecting against, arrived at differently.

`level` is part of the paper key because RI 2024 H1 P1 shares school, year and
paper_number with the H2 paper.

`content_text` is updated alongside `content_html` whenever it changed:
content_search is generated from content_text, so updating only the markup
leaves search reflecting the old wording (handoff SS6D makes the same point
about the admin inline editor). `options` goes with them for the same reason --
chem_search_doc takes it too, and RI 2024 H2 P1 Q8's options changed from
"[structure A]" to the graphs' real captions.

ASSETS
------
Each patched question's question_assets rows are RESYNCED: deleted, then
re-inserted from the new plan. Not an optimisation -- a correctness one. A
question can lose a figure between extractions (Q12's enthalpy table, which
turned out to be printed twice and is now dropped in corrections.py), and an
UPDATE-only patch would leave its row behind pointing at a file that is no
longer uploaded. question_assets has NO unique constraint (handoff SS8), so
delete-then-insert is the only way to make the rows match the plan exactly;
an upsert has nothing to conflict on.

A question in `qnums` with no assets in the plan is therefore emptied, which
is intended. Deleting the orphaned OBJECT from storage is a separate manual
step -- the migration cannot reach the bucket.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

SCHOOL, YEAR, PAPER, LEVEL = "RI", 2024, 1, "H2"
TAG = "$qp$"


def _lit(s: str) -> str:
    if TAG in s:
        raise SystemExit("dollar-quote tag %s occurs inside a value" % TAG)
    return TAG + s + TAG


def main(outdir: str, qnums: str, dest: str, prev: str | None = None):
    rows = {r["question_number"]: r for r in json.loads(
        (Path(outdir) / "questions.json").read_text(encoding="utf-8"))}
    plan = json.loads(
        (Path(outdir) / "asset_plan.json").read_text(encoding="utf-8"))
    want = [int(x) for x in qnums.split(",") if x.strip()]
    missing = [q for q in want if q not in rows]
    if missing:
        raise SystemExit("no extracted row for questions %s" % missing)

    where = ("p.school = '%s' AND p.year = %d AND p.paper_number = %d "
             "AND p.level = '%s'" % (SCHOOL, YEAR, PAPER, LEVEL))

    L: list = []
    add = L.append
    add("-- %s %d %s P%d -- markup patch for question(s) %s"
        % (SCHOOL, YEAR, LEVEL, PAPER, ", ".join(str(q) for q in want)))
    add("-- Generated by gen_patch_migration.py. DRY RUN: ends in ROLLBACK.")
    add("")
    add("BEGIN;")
    add("")
    add("DO $preflight$")
    add("DECLARE n int;")
    add("BEGIN")
    add("  SELECT count(*) INTO n FROM questions q JOIN papers p ON p.id = q.paper_id")
    add("   WHERE %s AND q.type = 'mcq'" % where)
    add("     AND q.question_number IN (%s);" % ", ".join(str(q) for q in want))
    add("  IF n <> %d THEN" % len(want))
    add("    RAISE EXCEPTION 'expected %d question(s) to patch, matched %%', n;"
        % len(want))
    add("  END IF;")
    add("END")
    add("$preflight$;")
    add("")
    for q in want:
        r = rows[q]
        add("UPDATE questions q SET content_html = %s,"
            % _lit(r["content_html"]))
        add("                       content_text = %s," % _lit(r["content_text"]))
        add("                       options      = %s::jsonb"
            % _lit(json.dumps(r["options"], ensure_ascii=False)))
        add("  FROM papers p")
        add(" WHERE p.id = q.paper_id AND %s" % where)
        add("   AND q.type = 'mcq' AND q.question_number = %d" % q)
        add(" RETURNING q.question_number, length(q.content_html) AS html_chars,")
        add("           q.content_search IS NOT NULL AS searchable;")
        add("")

    qsel = ("SELECT q.id FROM questions q JOIN papers p ON p.id = q.paper_id\n"
            "         WHERE %s AND q.type = 'mcq'\n"
            "           AND q.question_number IN (%s)"
            % (where, ", ".join(str(q) for q in want)))
    add("-- Resync the asset rows for these questions -- see the module note.")
    add("DELETE FROM question_assets WHERE question_id IN (")
    add("  " + qsel.replace("\n", "\n  "))
    add(");")
    add("")
    arows = [a for a in plan if a["question"] in set(want)]
    if arows:
        add("INSERT INTO question_assets (question_id, slot, storage_path, ordinal)")
        add("SELECT q.id, a.slot, a.path, a.ord")
        add("  FROM questions q JOIN papers p ON p.id = q.paper_id")
        add("  JOIN (VALUES")
        add(",\n".join(
            "    (%d, %s, %s, %d)" % (a["question"], _lit(a["slot"]),
                                      _lit(a["storage_path"]), a["ordinal"])
            for a in sorted(arows, key=lambda a: (a["question"], a["ordinal"]))))
        add("  ) AS a(qn, slot, path, ord) ON a.qn = q.question_number")
        add(" WHERE %s AND q.type = 'mcq'" % where)
        add("RETURNING question_id, slot, storage_path, ordinal;")
        add("-- Expect %d asset row(s) returned." % len(arows))
    else:
        add("-- No assets planned for any patched question: the DELETE is all.")
    add("")
    # An ORPHAN warning is only worth printing for a figure that actually went
    # away. Without the previous plan to compare against, every question that
    # never had a figure reads as one that just lost them, and a warning that
    # cries wolf on three questions out of seven gets skimmed past on the one
    # that matters.
    if prev:
        old = json.loads(
            (Path(prev) / "asset_plan.json").read_text(encoding="utf-8"))
        now = {(a["question"], a["storage_path"]) for a in plan}
        gone = sorted({(a["question"], a["storage_path"]) for a in old
                       if a["question"] in set(want)} - now)
        for q, path in gone:
            add("-- ORPHANED BY THIS PATCH: Q%d's %s is no longer referenced."
                " Delete the object from the bucket by hand." % (q, path))
        if gone:
            add("")
    add("-- Flip to COMMIT when the above looks right.")
    add("ROLLBACK;")
    add("")
    add("-- VERIFICATION -- run SEPARATELY, after COMMIT:")
    add("-- select q.question_number, length(q.content_html) as html_chars,")
    add("--        q.content_search is not null as searchable, q.options,")
    add("--        count(a.id) as assets,")
    add("--        string_agg(a.slot, ',' order by a.ordinal) as slots")
    add("--   from questions q join papers p on p.id = q.paper_id")
    add("--   left join question_assets a on a.question_id = q.id")
    add("--  where %s and q.question_number in (%s)"
        % (where, ", ".join(str(q) for q in want)))
    add("--  group by q.question_number, q.content_html, q.content_search,")
    add("--           q.options order by q.question_number;")

    bad = [l for l in L if "%%" in l]
    if bad:
        raise SystemExit("emitted SQL contains a literal %%%%:\n  " + "\n  ".join(bad))
    Path(dest).write_text("\n".join(L) + "\n", encoding="utf-8")
    print("wrote", dest)
    print("  %d question(s) patched" % len(want))


if __name__ == "__main__":
    main(*sys.argv[1:5])
