#!/usr/bin/env python3
"""Emit the question_los migration for a tagged MCQ paper.

Separate from the content migration because the two are settled at different
times: the content is mechanical, the tags are the user's editorial judgement
and arrive later.

THE FAILURE THIS GUARDS AGAINST
-------------------------------
Tags are inserted by JOINING on `learning_objectives.section_code`. A code that
does not exist -- a typo, or a 9729 code that 9476 dropped -- matches no row, so
the join produces nothing and the tag is SILENTLY DROPPED. The insert succeeds,
reports fewer rows than expected, and nobody notices which question lost its
tag. So the exact expected count is asserted after the insert, and the
transaction aborts if it is short.

SECOND FAILURE THIS GUARDS AGAINST (found on RI 2024 H2 P1, HANDOFF.md SS13):
`question_topics` LOOKS like it should be derived by the database from
`question_los`, but it isn't -- it's a separate table the FRONTEND keeps in
step via `syncTopics()` (index.html), which only runs after a tag edit made
in the UI. A SQL migration bypasses that silently: the tags land in
`question_los`, but every question shows its LO chip and an UNTAGGED badge at
the same time, and sorts/filters into no topic at all. So this generator
rebuilds `question_topics` itself (delete + reinsert, scoped to this paper)
right after the tags insert, and asserts no tagged question is left topic-less.

Other conventions carried over (handoff SS8, SS11):

* The question join pins `q.type = 'mcq'`. MCQ and structured share
  question_number, so a join on number alone can attach an MCQ's tags to a
  structured question of the same number in another paper.

* `question_los` IS uniqueness-protected, but by a STANDALONE INDEX
  (question_los_uniq on (question_id, lo_id, COALESCE(part_label,''))), not a
  constraint -- `pg_constraint` does not list it. ON CONFLICT against an
  expression index is fragile, so a re-run is refused by pre-flight instead.

* `classified_by` defaults to 'ai'. These tags are the user's own, made by hand,
  so it is set to 'human' -- otherwise the provenance of every tag in the bank
  becomes untrustworthy the moment anyone checks that column.

Usage:
  python3 -m ingest.gen_tag_migration <tags.json> <dest.sql> [--school ..] [...]

tags.json: {"<question_number>": ["7(f)(i)", ...], ...}

School/year/paper/level/syllabus default to the values this script was
originally written for (RI 2024 H2 P1), so an old invocation keeps working
unchanged -- same convention as gen_question_migration.py and
gen_patch_migration.py.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path


def main(tagfile: str, dest: str, *, school: str = "RI", year: int = 2024,
        paper: int = 1, level: str = "H2", syllabus: str = "H2"):
    SCHOOL, YEAR, PAPER, LEVEL, SYLLABUS = school, year, paper, level, syllabus
    tags = json.loads(Path(tagfile).read_text(encoding="utf-8"))
    pairs = sorted(((int(q), c) for q, cs in tags.items() for c in cs))
    n = len(pairs)
    if len({(q, c) for q, c in pairs}) != n:
        raise SystemExit("duplicate (question, code) pairs in the tag file")

    where = ("p.school = '%s' AND p.year = %d AND p.paper_number = %d "
             "AND p.level = '%s'" % (SCHOOL, YEAR, PAPER, LEVEL))

    L: list = []
    add = L.append
    add("-- %s %d %s P%d -- question_los for %d questions, %d tag rows"
        % (SCHOOL, YEAR, LEVEL, PAPER, len(tags), n))
    add("-- Generated by gen_tag_migration.py. DRY RUN: ends in ROLLBACK.")
    add("-- Run the CONTENT migration first; this one needs the questions.")
    add("")
    add("BEGIN;")
    add("")
    add("DO $preflight$")
    add("DECLARE n int;")
    add("BEGIN")
    add("  SELECT count(*) INTO n FROM questions q JOIN papers p ON p.id = q.paper_id")
    add("   WHERE %s AND q.type = 'mcq';" % where)
    add("  IF n <> %d THEN" % len(tags))
    add("    RAISE EXCEPTION 'expected %d tagged questions, found %%', n;" % len(tags))
    add("  END IF;")
    add("")
    add("  -- already tagged? a re-run would add a second copy of every tag that")
    add("  -- differs from an existing one, and be refused for the rest.")
    add("  SELECT count(*) INTO n FROM question_los l")
    add("    JOIN questions q ON q.id = l.question_id")
    add("    JOIN papers p ON p.id = q.paper_id")
    add("   WHERE %s;" % where)
    add("  IF n <> 0 THEN")
    add("    RAISE EXCEPTION 'this paper already has % question_los row(s)', n;")
    add("  END IF;")
    add("END")
    add("$preflight$;")
    add("")
    add("-- ---------------------------------------------------------------")
    add("-- Insert. An unresolvable section_code joins to nothing and vanishes,")
    add("-- so the count is asserted immediately afterwards.")
    add("-- ---------------------------------------------------------------")
    add("INSERT INTO question_los (question_id, lo_id, part_label)")
    add("SELECT q.id, lo.id, NULL")
    add("  FROM (VALUES")
    add(",\n".join("    (%d, '%s')" % (q, c) for q, c in pairs))
    add("  ) AS t(qn, code)")
    add("  JOIN papers p ON %s" % where)
    add("  JOIN questions q ON q.paper_id = p.id AND q.question_number = t.qn")
    add("                  AND q.type = 'mcq'")
    add("  JOIN learning_objectives lo ON lo.section_code = t.code")
    add("                             AND lo.syllabus = '%s'" % SYLLABUS)
    add("RETURNING question_id, lo_id;")
    add("")
    add("DO $check$")
    add("DECLARE n int;")
    add("BEGIN")
    add("  SELECT count(*) INTO n FROM question_los l")
    add("    JOIN questions q ON q.id = l.question_id")
    add("    JOIN papers p ON p.id = q.paper_id")
    add("   WHERE %s;" % where)
    add("  IF n <> %d THEN" % n)
    add("    RAISE EXCEPTION 'inserted %% tag rows, expected %d -- a section_code "
        "did not resolve against learning_objectives and was dropped silently', n;"
        % n)
    add("  END IF;")
    add("END")
    add("$check$;")
    add("")
    add("-- ---------------------------------------------------------------")
    add("-- question_topics is DERIVED from question_los, but only the FRONTEND")
    add("-- keeps it in step (syncTopics() in index.html, run after a UI tag edit).")
    add("-- This SQL insert bypasses that entirely, so every tagged question would")
    add("-- otherwise show its LO chip and an UNTAGGED badge at once, and sort into")
    add("-- no topic. Rebuilt here, scoped to this paper's questions only.")
    add("-- ---------------------------------------------------------------")
    add("DELETE FROM question_topics qt")
    add(" USING questions q, papers p")
    add(" WHERE qt.question_id = q.id AND q.paper_id = p.id AND %s;" % where)
    add("")
    add("INSERT INTO question_topics (question_id, topic_id)")
    add("SELECT DISTINCT l.question_id, lo.topic_id")
    add("  FROM question_los l")
    add("  JOIN questions q ON q.id = l.question_id")
    add("  JOIN papers p ON p.id = q.paper_id")
    add("  JOIN learning_objectives lo ON lo.id = l.lo_id")
    add(" WHERE %s AND lo.topic_id IS NOT NULL;" % where)
    add("")
    add("DO $topics_check$")
    add("DECLARE orphans int;")
    add("BEGIN")
    add("  SELECT count(*) INTO orphans FROM (")
    add("    SELECT DISTINCT l.question_id FROM question_los l")
    add("      JOIN questions q ON q.id = l.question_id")
    add("      JOIN papers p ON p.id = q.paper_id")
    add("     WHERE %s" % where)
    add("  ) tagged")
    add("  WHERE NOT EXISTS (SELECT 1 FROM question_topics qt WHERE qt.question_id = tagged.question_id);")
    add("  IF orphans <> 0 THEN")
    add("    RAISE EXCEPTION '% tagged question(s) have no topic row -- their LO(s) likely have a NULL topic_id', orphans;")
    add("  END IF;")
    add("END")
    add("$topics_check$;")
    add("")
    add("-- These tags are the user's own, made by hand. classified_by defaults")
    add("-- to 'ai', which would misreport the provenance of every one of them.")
    add("UPDATE questions q SET classified_by = 'human'")
    add("  FROM papers p")
    add(" WHERE p.id = q.paper_id AND %s AND q.type = 'mcq'" % where)
    add(" RETURNING q.question_number, q.classified_by;")
    add("")
    add("-- Flip to COMMIT when the above looks right.")
    add("ROLLBACK;")
    add("")
    add("-- ---------------------------------------------------------------")
    add("-- VERIFICATION -- run SEPARATELY, after COMMIT.")
    add("-- ---------------------------------------------------------------")
    add("-- select q.question_number,")
    add("--        string_agg(lo.section_code, ', ' order by lo.section_code) as los")
    add("--   from question_los l")
    add("--   join questions q on q.id = l.question_id")
    add("--   join papers p on p.id = q.paper_id")
    add("--   join learning_objectives lo on lo.id = l.lo_id")
    add("--  where %s" % where)
    add("--  group by q.question_number order by q.question_number;")
    add("-- Expect %d rows totalling %d tags." % (len(tags), n))

    bad = [l for l in L if "%%" in l]
    if bad:
        raise SystemExit(
            "emitted SQL contains a literal %%%% -- in PL/pgSQL that is an "
            "escaped percent, not a placeholder, so RAISE gets one argument "
            "too many and the whole transaction aborts:\n  " + "\n  ".join(bad))
    Path(dest).write_text("\n".join(L) + "\n", encoding="utf-8")
    print("wrote", dest)
    print("  %d questions, %d tag rows" % (len(tags), n))


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("tagfile")
    ap.add_argument("dest")
    ap.add_argument("--school", default="RI")
    ap.add_argument("--year", type=int, default=2024)
    ap.add_argument("--paper", type=int, default=1)
    ap.add_argument("--level", default="H2")
    ap.add_argument("--syllabus", default="H2")
    a = ap.parse_args()
    main(a.tagfile, a.dest, school=a.school, year=a.year, paper=a.paper,
        level=a.level, syllabus=a.syllabus)
