#!/usr/bin/env python3
"""Emit the paper + questions + assets migration for an MCQ question paper.

Kept separate from `gen_migration.py`, which attaches worked solutions to
questions that ALREADY EXIST. This one creates them, so its guards are
different and its failure modes are worse: `gen_migration.py` can at worst
overwrite a worked solution, this can silently create a second copy of a whole
paper.

THE GUARDS, AND WHY EACH ONE IS THERE (handoff SS8, SS11)
--------------------------------------------------------
* `papers` has NO unique constraint on (school, year, paper_number) and neither
  does `questions` on (paper_id, question_number), so `ON CONFLICT` is not
  available and a second run duplicates everything in silence. Hence an
  explicit RAISE EXCEPTION pre-flight.

* RI 2024 **H1** P1 is already live. School, year and paper_number are all
  identical to the paper being inserted here; only `level` differs. A guard
  that forgot `level` would either refuse the insert or, worse, be written
  loosely enough to attach 30 H2 questions to the H1 paper.

* `papers.status` and `questions.status` both DEFAULT to 'pending', and the
  read policy is `is_allowed() AND (status='approved' OR is_reviewer())`. Left
  at the default the paper inserts, reports success, and is invisible to every
  colleague who is not a reviewer. Both are set explicitly.

* `content_text` must be non-null or the question is invisible to search:
  content_search is generated from (content_text, keywords, options) and
  `content_html` is NOT an input.

* The whole thing is ONE statement built from data-modifying CTEs, so the paper,
  its questions and their assets cannot be partially applied. Supabase's linter
  warns "creates a table without enabling RLS" for this shape -- a known false
  positive (handoff SS4), no table is created.

Usage:
  python3 -m ingest.gen_question_migration <outdir> <answer_key.json> <dest.sql>
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

SCHOOL, YEAR, PAPER, LEVEL = "RI", 2024, 1, "H2"
ASSESSMENT = "prelim"
TAG = "$qh$"


def _lit(s: str) -> str:
    """Dollar-quote a value, having checked the delimiter is not inside it.

    Handoff SS11: test for the ACTUAL tag, not a substring of it.
    """
    if TAG in s:
        raise SystemExit("dollar-quote tag %s occurs inside a value" % TAG)
    return TAG + s + TAG


def main(outdir: str, keyfile: str, dest: str):
    out = Path(outdir)
    rows = json.loads((out / "questions.json").read_text(encoding="utf-8"))
    plan = json.loads((out / "asset_plan.json").read_text(encoding="utf-8"))
    keys = json.loads(Path(keyfile).read_text(encoding="utf-8"))

    missing = [r["question_number"] for r in rows
               if str(r["question_number"]) not in keys]
    if missing:
        raise SystemExit("no answer key for questions %s" % missing)

    L: list = []
    add = L.append
    add("-- %s %d %s Paper %d -- paper + %d questions + %d assets"
        % (SCHOOL, YEAR, LEVEL, PAPER, len(rows), len(plan)))
    add("-- Generated by gen_question_migration.py. DRY RUN: ends in ROLLBACK.")
    add("-- Flip ROLLBACK to COMMIT once the output looks right, then confirm")
    add("-- with the SEPARATE verification SELECT at the bottom (SS9: a dry run")
    add("-- and a real commit print identical output).")
    add("")
    add("BEGIN;")
    add("")
    add("-- ---------------------------------------------------------------")
    add("-- PRE-FLIGHT. No unique constraint exists on papers or questions,")
    add("-- so a second run would duplicate the entire paper in silence.")
    add("-- ---------------------------------------------------------------")
    add("DO $preflight$")
    add("DECLARE n int;")
    add("BEGIN")
    add("  -- 1. this exact paper must not already be loaded. LEVEL is part of")
    add("  --    the key: RI 2024 H1 Paper 1 is already live and shares school,")
    add("  --    year and paper_number with this one.")
    add("  SELECT count(*) INTO n FROM papers")
    add("   WHERE school = %s AND year = %d AND paper_number = %d"
        % (_lit(SCHOOL), YEAR, PAPER))
    add("     AND level = '%s';" % LEVEL)
    add("  IF n <> 0 THEN")
    add("    RAISE EXCEPTION '%s %d %s P%d is already loaded (%% paper row(s)) "
        "-- re-running would duplicate it', n;" % (SCHOOL, YEAR, LEVEL, PAPER))
    add("  END IF;")
    add("")
    add("  -- 2. the H1 paper of the same number must be left alone. This is a")
    add("  --    tripwire, not a requirement: if it is missing, something about")
    add("  --    the data is not what this migration was written against.")
    add("  SELECT count(*) INTO n FROM papers")
    add("   WHERE school = %s AND year = %d AND paper_number = %d AND level = 'H1';"
        % (_lit(SCHOOL), YEAR, PAPER))
    add("  IF n <> 1 THEN")
    add("    RAISE WARNING 'expected exactly 1 RI 2024 H1 P1 paper, found %', n;")
    add("  END IF;")
    add("END")
    add("$preflight$;")
    add("")
    add("-- ---------------------------------------------------------------")
    add("-- One statement: paper, questions and assets, or none of them.")
    add("-- status is set EXPLICITLY on both paper and questions -- the column")
    add("-- defaults to 'pending', which inserts fine and is then invisible to")
    add("-- every non-reviewer.")
    add("-- ---------------------------------------------------------------")
    add("WITH p AS (")
    add("  INSERT INTO papers (school, year, paper_number, level, paper_name,")
    add("                      is_prelim, assessment_type, status, source_type)")
    add("  VALUES (%s, %d, %d, '%s', NULL, true, '%s', 'approved', 'docx')"
        % (_lit(SCHOOL), YEAR, PAPER, LEVEL, ASSESSMENT))
    add("  RETURNING id")
    add("), q AS (")
    add("  INSERT INTO questions (paper_id, type, question_number, content_html,")
    add("                         content_text, options, answer_key, marks, status)")
    add("  SELECT p.id, 'mcq', v.qn, v.html, v.txt, v.opts::jsonb, v.akey, 1, 'approved'")
    add("    FROM p, (VALUES")
    vals = []
    for r in sorted(rows, key=lambda r: r["question_number"]):
        qn = r["question_number"]
        vals.append("      (%d, %s, %s, %s, %s)"
                    % (qn, _lit(r["content_html"]), _lit(r["content_text"]),
                       _lit(json.dumps(r["options"], ensure_ascii=False)),
                       _lit(keys[str(qn)])))
    add(",\n".join(vals))
    add("    ) AS v(qn, html, txt, opts, akey)")
    add("  RETURNING id, question_number")
    add(")")
    add("INSERT INTO question_assets (question_id, slot, storage_path, ordinal)")
    add("SELECT q.id, a.slot, a.path, a.ord")
    add("  FROM q JOIN (VALUES")
    arows = []
    for a in sorted(plan, key=lambda a: (a["question"], a["ordinal"])):
        arows.append("    (%d, %s, %s, %d)"
                     % (a["question"], _lit(a["slot"]),
                        _lit(a["storage_path"]), a["ordinal"]))
    add(",\n".join(arows))
    add("  ) AS a(qn, slot, path, ord) ON a.qn = q.question_number")
    add("RETURNING question_id, slot, storage_path, ordinal;")
    add("")
    add("-- Expect %d asset rows returned." % len(plan))
    add("")
    add("-- Flip to COMMIT when the above looks right.")
    add("ROLLBACK;")
    add("")
    add("-- ---------------------------------------------------------------")
    add("-- VERIFICATION -- run SEPARATELY, after COMMIT.")
    add("-- ---------------------------------------------------------------")
    add("-- select q.question_number, q.answer_key, q.marks,")
    add("--        length(q.content_html)              as html_chars,")
    add("--        length(q.content_text)              as text_chars,")
    add("--        q.content_search is not null        as searchable,")
    add("--        count(a.id)                         as assets,")
    add("--        string_agg(a.slot, ',' order by a.ordinal) as slots")
    add("--   from questions q")
    add("--   left join question_assets a on a.question_id = q.id")
    add("--   join papers p on p.id = q.paper_id")
    add("--  where p.school = 'RI' and p.year = 2024")
    add("--    and p.paper_number = 1 and p.level = 'H2'")
    add("--  group by q.question_number, q.answer_key, q.marks,")
    add("--           q.content_html, q.content_text, q.content_search")
    add("--  order by q.question_number;")
    add("-- Expect 30 rows, every searchable = true, %d assets in total."
        % len(plan))

    bad = [l for l in L if "%%" in l]
    if bad:
        raise SystemExit("emitted SQL contains a literal %%%% -- see "
                         "gen_tag_migration.py:\n  " + "\n  ".join(bad))
    Path(dest).write_text("\n".join(L) + "\n", encoding="utf-8")
    print("wrote", dest)
    print("  1 paper, %d questions, %d assets" % (len(rows), len(plan)))


if __name__ == "__main__":
    main(*sys.argv[1:4])
